# LS증권(xing) API 접속 정보
LS_API:
  APP_KEY: "PSFBKxCSDcCNu71O8YguohrmduY5WNrLObSu"
  APP_SECRET: "NW69awZmzWBGPBhnhFbrPrJKnuhYIGCx"
  USER_ID: "로그인_아이디"
  USER_PW: "로그인_비밀번호"
  CERT_PW: "공인인증서_비밀번호"
  MODE: "real"  # 실전매매는 real, 모의투자는 paper